name: chorganizer
description: A complete app to fill in any gaps

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0

  image_picker:
  sqflite:
  path:
  transparent_image:
  flutter_local_notifications:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
